### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by w22w1** [ROZ-MOFUMOFU-ME/zny-nomp#40]
hello, i have this error. i have try with node 8.11/9/10/12/14.5/15.6
can you help me please

/root/poo/node_modules/bitcoinjs-lib/src/address.js:89
  throw new Error(address + ' has no matching Script');
  ^

Error: undefined has no matching Script
    at Object.toOutputScript (/root/poo/node_modules/bitcoinjs-lib/src/address.js:89:9)
    at Object.exports.addressToScript (/root/poo/node_modules/stratum-pool/lib/util.js:266:32)
    at generateOutputTransactions (/root/poo/node_modules/stratum-pool/lib/transactions.js:42:36)
    at Object.exports.CreateGeneration (/root/poo/node_modules/stratum-pool/lib/transactions.js:239:30)
    at new BlockTemplate (/root/poo/node_modules/stratum-pool/lib/blockTemplate.js:75:47)
    at JobManager.processTemplate (/root/poo/node_modules/stratum-pool/lib/jobManager.js:185:32)
    at /root/poo/node_modules/stratum-pool/lib/pool.js:635:62
    at itemFinished (/root/poo/node_modules/stratum-pool/lib/daemon.js:162:36)
    at /root/poo/node_modules/stratum-pool/lib/daemon.js:184:17
    at parseJson (/root/poo/node_modules/stratum-pool/lib/daemon.js:91:17)

**Comment by Gauthier-TorchetBianchi** [comment]
SprintPay coin (yespower)

**Comment by Gauthier-TorchetBianchi** [comment]
i had try to install it on 3 servers (ubuntu 16 - 20.04 - 2.10) with 10 versions of node but don't work. always this error

**Comment by Gauthier-TorchetBianchi** [comment]
?
