### ISSUE TITLE
yespowerurx

### ISSUE THREAD

**Issue by mitchngwen** [ROZ-MOFUMOFU-ME/zny-nomp#45]
I added added Uranium x coin with yespowerurx and I get an error saying it's unsupported. I used instead just yespower and all my workers can connect and shares are excepted but never find a block. Is there an addon or a work around to be able to mine Uraniumx? I chose your pool software because other pools use it to for there Uraniumx mining pool.

**Comment by mitchngwen** [comment]
Could I twist your arm to add yespowerurx?

**Comment by mitchngwen** [comment]
After many hours of hassling with it, I thought I got it to work and then this happens:

/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/algoProperties.js:369
                return multiHashing.yespower_urx(data, nValue, rValue);
                                    ^

TypeError: multiHashing.yespower_urx is not a function
    at /home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/algoProperties.js:369:37
    at JobManager.processShare (/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/jobManager.js:254:26)
    at StratumClient.<anonymous> (/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/pool.js:554:47)
    at StratumClient.emit (events.js:326:22)
    at handleSubmit (/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/stratum.js:210:15)
    at handleMessage (/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/stratum.js:100:17)
    at /home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/stratum.js:290:25
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/gwenmine/redis-stable/zny-nomp/node_modules/stratum-pool/lib/stratum.js:276:26)

**Comment by ROZ-MOFUMOFU-ME** [comment]
https://github.com/ROZ-MOFUMOFU-ME/node-stratum-pool/commit/d13af0d31482116cfc5e4b04a1ec10d5e66cf786
You can also refer to this
